# Generated by Django 5.2.8 on 2026-01-12 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(help_text='Ej: FNC, G2, T1', max_length=10, unique=True)),
                ('logo', models.CharField(blank=True, help_text='URL del logo', max_length=255)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('genero', models.CharField(choices=[('MOBA', 'MOBA (League of Legends, Dota 2)'), ('FPS', 'First Person Shooter'), ('BR', 'Battle Royale'), ('FIG', 'Juegos de Lucha'), ('STR', 'Estrategia en Tiempo Real')], max_length=4)),
                ('desarrollador', models.CharField(max_length=100)),
                ('imagen_portada', models.CharField(blank=True, help_text='URL de la imagen', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Nombre en juego')),
                ('avatar', models.CharField(blank=True, help_text='URL de la imagen', max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('rango_actual', models.CharField(choices=[('BRO', 'Bronce'), ('PLT', 'Plata'), ('ORO', 'Oro'), ('PLA', 'Platino'), ('DIA', 'Diamante'), ('MAS', 'Maestro'), ('GM', 'Gran Maestro'), ('CHA', 'Challenger')], default='BRO', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_id', models.ForeignKey(blank=True, db_column='equipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='juegos.equipo')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-rango_actual', 'nickname'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador_id',
            field=models.ForeignKey(blank=True, db_column='jugador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_liderado', to='juegos.jugador'),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('posicion_final', models.IntegerField(blank=True, help_text='Posición final en el torneo (1=Campeón)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('premio_ganado', models.DecimalField(decimal_places=2, default=0.0, help_text='Premio obtenido en USD', max_digits=10)),
                ('puntos_obtenidos', models.IntegerField(default=0, help_text='Puntos de ranking conseguidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, to='juegos.equipo')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['torneo_id', 'posicion_final'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('premio_total', models.DecimalField(decimal_places=2, help_text='Premio total en USD', max_digits=10)),
                ('modalidad', models.CharField(choices=[('LIG', 'Liga (Todos contra todos)'), ('ELI', 'Eliminación Directa'), ('GRP', 'Fase de Grupos + Playoffs')], max_length=3)),
                ('max_equipos', models.IntegerField(help_text='Número máximo de equipos participantes', validators=[django.core.validators.MinValueValidator(2)])),
                ('estado', models.CharField(choices=[('INS', 'Abierto a inscripciones'), ('CUR', 'En curso'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='INS', max_length=3)),
                ('ubicacion', models.CharField(help_text="Ciudad o 'Online'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipos', models.ManyToManyField(through='juegos.Participacion', to='juegos.equipo')),
                ('juego_id', models.ForeignKey(db_column='juego_id', on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='juegos.juego')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='participacion',
            name='torneo_id',
            field=models.ForeignKey(db_column='torneo_id', on_delete=django.db.models.deletion.CASCADE, to='juegos.torneo'),
        ),
        migrations.AddConstraint(
            model_name='participacion',
            constraint=models.UniqueConstraint(fields=('equipo_id', 'torneo_id'), name='unique_participacion_equipo_torneo'),
        ),
    ]
